---
  - name: Configurar entorno de monitoreo en CentOS 9
    hosts: all
    become: yes
    tasks:
      - name: Crear carpetas de configuración de Prometheus y Grafana
        ansible.builtin.file:
          path: "{{ item }}"
          state: directory
          mode: '0755'
        loop:
          - /home/santit/docker/prometheus
          - /home/santit/docker/grafana/provisioning/datasources
  
      - name: Cambiar permisos de las carpetas de configuración
        ansible.builtin.command:
          cmd: "chmod -R 777 {{ item }}"
        loop:
          - /home/santit/docker/prometheus
          - /home/santit/docker/grafana
  
      - name: Copiar archivo prometheus.yml
        ansible.builtin.copy:
          dest: /home/santit/docker/prometheus/prometheus.yml
          content: |
            global:
              scrape_interval: 1m
            scrape_configs:
              - job_name: "prometheus"
                scrape_interval: 1m
                static_configs:
                - targets: ["localhost:9090"]
              - job_name: "node"
                static_configs:
                - targets: ["node-exporter:9100"]
              - job_name: "cadvisor"
                scrape_interval: 5s
                static_configs:
                - targets: ["10.1.149.19:8081"]
              - job_name: "hvhost01"
                scrape_interval: 5s
                static_configs:
                - targets: ["10.1.149.191:9182"]
  
      - name: Copiar archivo de Docker Compose
        ansible.builtin.copy:
          dest: /home/santit/docker/docker-compose.yml
          content: |
            version: '3.8'
            networks:
              monitoring:
                driver: bridge
            volumes:
              prometheus_data: {}
            services:
              node-exporter:
                image: prom/node-exporter:latest
                container_name: node-exporter
                restart: unless-stopped
                volumes:
                  - /proc:/host/proc:ro
                  - /sys:/host/sys:ro
                  - /:/rootfs:ro
                command:
                  - '--path.procfs=/host/proc'
                  - '--path.rootfs=/rootfs'
                  - '--path.sysfs=/host/sys'
                  - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
                ports:
                  - 9100:9100
                networks:
                  - monitoring
              prometheus:
                image: prom/prometheus:latest
                container_name: prometheus
                restart: unless-stopped
                volumes:
                  - /home/santit/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
                  - /home/santit/docker/prometheus:/prometheus
                command:
                  - '--config.file=/etc/prometheus/prometheus.yml'
                  - '--storage.tsdb.path=/prometheus'
                  - '--web.console.libraries=/etc/prometheus/console_libraries'
                  - '--web.console.templates=/etc/prometheus/consoles'
                  - '--web.enable-lifecycle'
                ports:
                  - 9090:9090
                networks:
                  - monitoring
              grafana:
                image: grafana/grafana:latest
                container_name: grafana
                ports:
                  - 3000:3000
                restart: unless-stopped
                volumes:
                  - /home/santit/docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
                  - /home/santit/docker/grafana:/var/lib/grafana
                networks:
                  - monitoring
              cadvisor:
                image: gcr.io/cadvisor/cadvisor:latest
                container_name: cadvisor
                ports:
                  - 8081:8080
                networks:
                  - monitoring
                volumes:
                  - /:/rootfs:ro
                  - /var/run:/var/run:rw
                  - /sys:/sys:ro
                  - /var/lib/docker/:/var/lib/docker:ro
                depends_on:
                  - redis
              redis:
                image: redis:latest
                container_name: redis
                ports:
                  - 6379:6379
                networks:
                  - monitoring
  
      - name: Levantar servicios con Docker Compose
        ansible.builtin.shell: |
          /usr/local/bin/docker-compose -f /home/santit/docker/docker-compose.yml up -d
        args:
          chdir: /home/santit/docker